### ISSUE TITLE
AssertionError: can only test a child process

### ISSUE THREAD

**Issue by ZWEQHLWY** [wbhu/Tri-MipRF#12]
when i run the script of chair，everything is ok。but in drums  i meet this erro，and the PSNR  can not achieve the normal score。Is this error causing the impact。
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__
    self._shutdown_workers()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1449, in _shutdown_workers
    if w.is_alive():
  File "/root/miniconda3/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f7e6ba823a0>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__
    self._shutdown_workers()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1449, in _shutdown_workers
    if w.is_alive():
  File "/root/miniconda3/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
100%|███████████████████████████████████████████████████████| 800/800 [01:47<00:00,  7.47it/s]
2023-10-12 09:13:52.710 | INFO     | trainer.trainer:eval:186 - ==> Evaluation done
2023-10-12 09:13:52.711 | INFO     | utils.writer:write_scalar_dicts:79 - num_alive_ray:64939.67125 rendering_samples_actual:24635.15625 num_rays:375.0 PSNR:28.454062707424164 

looking forward to your reply

**Comment by ZWEQHLWY** [comment]
> The AssertionError seems a bug (https://discuss.pytorch.org/t/error-while-multiprocessing-in-dataloader/46845/8), but it should not influence the results, The PSNR of drums in multi-scale blender dataset should be ~28.55 as reported in Tab.4 of the paper (supp)

Thanks
